apiVersion: v1
kind: Service
metadata:
  name: appointment-service
  namespace: ns-appointment-service
  labels:
    app: appointment-service
spec:
  type: LoadBalancer
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
  selector:
    app: appointment-service