@startuml feedback_appointment

title Envio de Feedback

actor "User" as user
participant "Appointment Service" as appointment_service
queue "Feedback Topic" as topic
participant "Database" as database

note over user
Neste exemplo, o usuário deve
ser um **paciente**.
end note

user -> appointment_service: POST /appointments/{appointmentId}/feedbacks\n(Bearer JWT)

activate appointment_service
appointment_service -> appointment_service: Deve ser informada uma nota\ne um comentário
appointment_service -> database: Carregar a consulta
database --> appointment_service: Retorna a consulta
appointment_service -> appointment_service: Criar um novo evento de feedback
appointment_service -> topic: Enviar um evento com\nos detalhes do feedback
topic --> appointment_service: Retornar o ID da mensagem
appointment_service -> database: Armazenar os detalhes do evento
database --> appointment_service: Evento armazenado
appointment_service --> user: 201 Criado
deactivate appointment_service


@enduml